### ISSUE TITLE
Добавить в миграцию инфоблока настройки вкладки "Журнал событий".

### ISSUE THREAD

**Issue by SkeitOl** [andreyryabin/sprint.migration#101]
Если создавать миграцию через "Создать миграцию для инфоблока", то настройки инфоблока во вкладке "Журнал событий" не переносятся.
![image](https://user-images.githubusercontent.com/91635881/188864467-8a1dedf5-6bc9-4def-b992-603ffc2d8879.png)

**Comment by andreyryabin** [comment]
решено в 4.2.1
