### ISSUE TITLE
Не переносится настройка свойства "Показывать в умном фильтре"

### ISSUE THREAD

**Issue by SkeitOl** [andreyryabin/sprint.migration#102]
При создании миграции через "Создать миграцию для инфоблока" не переноситься настройка свойства "Показывать в умном фильтре"
![image](https://user-images.githubusercontent.com/91635881/189482071-d71dbdab-6f15-42ef-9065-3b82162a9152.png)

Версия модуля: 4.1.2

**Comment by andreyryabin** [comment]
исправлено
