### ISSUE TITLE
Привязанные элементы инфоблока переносятся со старыми ID

### ISSUE THREAD

**Issue by fenix63** [andreyryabin/sprint.migration#104]
Есть стенд-источник, с которого я хочу перенести элементы инфоблока. И есть стенд-приёмник, куда я миграцию устанавливаю.

На стенде-источнике есть инфоблок. У него есть свойство "Привязка к элементам инфоблока" - множественное. У элементов этого инфоблока это свойство заполнено какими-то значениями (Какими то ID). Создаю миграцию. Устанавливаю эту миграцию на стенд-приёмник. Элементы успешно создаются. Свойства тоже есть. Но в свойствах этих элементов указаны ID привязанных элементов со стенда-источника. А на стенде-приёмнике Битрикс дал привязанным элементам новые ID, и в итоге получается так, что при переносе сами элементы то перенеслись, а привязанные элементы - нет, потому что на новом стенде у них и ID новые.

Нужно, чтобы миграция при установке её на целевой стенд корректно идентифицировала элементы привязки и устанавливала правильные ID в свойстве с привязкой.

**Comment by andreyryabin** [comment]
решено в 4.2.1, вместо id элементов указываю уникальную строку с названием, xml_id и кодом, по которой будет происходить поиск совпадений
