### ISSUE TITLE
[Ux11] Ошибка описания модуля "sprint.migration"

### ISSUE THREAD

**Issue by Elnadrion** [andreyryabin/sprint.migration#105]
Привет. Вижу что вы добавили совместимость с PHP 8 в последней версии. Но модуль не устанавливается из Marketplace на сайте на PHP 8, т.к. этой совместимости не было в старых версиях

Ошибки:
![image](https://user-images.githubusercontent.com/33313896/204124236-aadbf78b-497a-4022-9b2c-8245d0eebd29.png)
![image](https://user-images.githubusercontent.com/33313896/204124240-38c5dfd6-8bf5-404b-bceb-ed9026487b96.png)

Ошибка конкретно в старом конструкторе в sprint.migration/install/index.php во всех версиях, кроме последней

**Comment by andreyryabin** [comment]
мне видимо стоит удалить все предыдущие версии с маркета, а вы попробуйте скачать модуль с гитхаба напрямую

**Comment by Elnadrion** [comment]
Да я установил :) Просто сделал тикет, чтобы вы знали про баг

**Comment by andreyryabin** [comment]
спасибо, я так и сделал, удалил все версии и загрузил полную с 4.1.3

**Comment by Elnadrion** [comment]
Спасибо, проверил на новом сайте на PHP 8 - все встало без проблем
