### ISSUE TITLE
Множественное поле типа текст

### ISSUE THREAD

**Issue by kto32** [andreyryabin/sprint.migration#111]
Добрые день, при миграции элементов инфоблока переносит пустым множественное свойство типа текст, в миграции поле в единичном экземпляре и пустое, Версия модуля: 4.2.4, куда можно качнуть вопрос?

**Comment by andreyryabin** [comment]
подскажите версию битрикса ещё и версию php, посмотрю на этой неделе

**Comment by kto32** [comment]
1С-Битрикс: Управление сайтом 22.200.200
php 7.4.15

**Comment by andreyryabin** [comment]
не смог воспроизвести в 4.6.1 , множественные html поля обновились корректно
