### ISSUE TITLE
Ошибка на создании группы пользователей

### ISSUE THREAD

**Issue by jasmanchik** [andreyryabin/sprint.migration#112]
<img width="498" alt="image" src="https://user-images.githubusercontent.com/40543800/224475837-4be6e7fd-4504-4c4d-9058-59c4827d2e96.png">
<img width="613" alt="image" src="https://user-images.githubusercontent.com/40543800/224475852-4450b127-7f8f-4446-bf6a-db1757d6ff2a.png">
Если удалить поле "SECURITY_POLICY" или присвоить ему строку, то все работает.

**Comment by andreyryabin** [comment]
Спасибо, перепроверю и поправлю, видимо апи поменялось

**Comment by andreyryabin** [comment]
Может модуль старой версии? на последней экспортируется в SECURITY_POLICY=>null
и с таким значением проблем нет

**Comment by jasmanchik** [comment]
модуль 4.2.2 
Миграция свежая
Возможно просто обновить модуль надо мне

**Comment by andreyryabin** [comment]
скорее поправьте саму миграцию

**Comment by andreyryabin** [comment]
добавил в 4.6.1 небольшую проверку  убирающую эту ошибку
