### ISSUE TITLE
Генерация кода с коротким синтаксисом массива и нормальными отступами

### ISSUE THREAD

**Issue by waleev** [andreyryabin/sprint.migration#118]
Сейчас, например, если сгенерить код для пользовательского поля, то массив, описывающий поле, будет содержать массивы вида array() и с поехавшими отступами.
Можно ли как-то навести красоту, чтобы сразу генерировался нормальный код, с [] и отступами?

**Comment by andreyryabin** [comment]
для этого используются библиотеки типа https://github.com/PHP-CS-Fixer/PHP-CS-Fixer
обычно они встроены в ide , но можно запускать и из консоли, они форматируют код на основе заданных настроек, отсупы, пробелы и т.д.

модуль же генерирует код без такого форматирования, используя функцию var_export , это наиболе простой и надежный способ выгрузить код в файл. 

В целом  подумаю над тем как интегрировать внешние "фиксеры" в модуль, может сделаю страничку в вики

**Comment by waleev** [comment]
Понял, спасибо!
