### ISSUE TITLE
Ошибка миграции HighloadBlock

### ISSUE THREAD

**Issue by Kiyte** [andreyryabin/sprint.migration#119]
1. Переносим HLB миграцией
2. Переходим к его настройке
3. При попытке изменить что либо (Название, Права доступа и т.д.) выскакивает ошибка

[Ошибка](https://joxi.ru/KAx3RJ5tw05Jn2)

автор: Alexey Razumyak

**Comment by andreyryabin** [comment]
не смог воспроизвести в 4.6.1, по моему ошибка вообще к модулю не относится, если возникает при редактировании
