### ISSUE TITLE
исключение при откате по умолчанию

### ISSUE THREAD

**Issue by andreyryabin** [andreyryabin/sprint.migration#128]
пустой откат по умолчанию…
мб сделать down(){ return false; } по умолчанию в шаблонизаторе?
если пишешь свою реализацию отката - опишешь свою логику и вернешь то что нужно, или void, а false - чтобы не откатывались миграции без описания самого отката

автор https://t.me/pu6elozed

**Comment by w1cerg** [comment]
Можно еще исключение кидать, я обычно так делаю, с текстом "Откат не преудсмотрен".
При этом всегда есть возможность отметить миграцию как новую, если нет желания править код миграции, в итоге никаких проблем глобально не должно быть.

**Comment by andreyryabin** [comment]
сделано для некоторых видов миграций
