### ISSUE TITLE
Миграция для пользовательских полей

### ISSUE THREAD

**Issue by Cleverscript** [andreyryabin/sprint.migration#130]
Приветствую! Спасибо за модуль!
На портале Bitrix24 очень много (тысячи) пользовательских полей по разным сущностям, и при создании миграции, они "вываливаются" все, из-за чего JS который все это обрабатывает, "вешает" вкладку браузера...
Было бы неплохо выводить поля только по нужным сущностям, т.е. как то по клику на сущности подгружать.
![Screenshot_20240618_123820](https://github.com/andreyryabin/sprint.migration/assets/204266/e23d2de2-6d3a-404f-a759-92f4a46b7804)

**Comment by andreyryabin** [comment]
Понял вас, возьму в работу

**Comment by andreyryabin** [comment]
Посмотрите версию 4.9.6 

добавил промежуточный пункт выбора объекта

![Selection_199](https://github.com/andreyryabin/sprint.migration/assets/5873964/acc20deb-dbbb-49c0-b8ae-56869b678ffb)
