### ISSUE TITLE
Миграция пользовательских полей

### ISSUE THREAD

**Issue by AleksandrImedia** [andreyryabin/sprint.migration#132]
При попытке мигрировать пользовательское поле, типа привязка к элементам хайлоадблоков, возникает ошибка экспорта в том случае, когда на сервере, где устанавливается миграция, у данного поля будет в БД задан ID хайлоада который факту он уже удален. И при получении в методе prepareExportUserTypeEntity (файл /bitrix/modules/sprint.migration/lib/helpers/usertypeentityhelper.php) https://take.ms/gou1q он не сможет получить этот удаленный хайлоад и выдаст ошибку экспорта поля.

В этом случае, возможно имеет смысл, игнорировать тот факт, что для истории при установке миграции, не нужно получать предыщущий хайлоад этого поля, его может и не быть.

**Comment by andreyryabin** [comment]
Здравствуйте. 
Если я правильно понял вы 
1) удалили справочник 
2) пытаетесь обновить пользовательское поле, в котором осталась к нему привязка

**Comment by AleksandrImedia** [comment]
Добрый день.

Вы обсолютно правы, справочник исчез другой миграцией, но вот поле было не обновлено. И ваше предложение на 100% верное, спасибо!

**Comment by andreyryabin** [comment]
да, надо поправить этот момент, эта привязка обновится на новое значение, никакого смысла выяснять валидно ли было старое нет

**Comment by Solo-it** [comment]
Есть информация, когда будет фикс?

**Comment by andreyryabin** [comment]
Спасибо что напомнили, посмотрю в ближайшую неделю

**Comment by andreyryabin** [comment]
исправлено в 4.16.1
