### ISSUE TITLE
Метаинформация о миграции

### ISSUE THREAD

**Issue by Cleverscript** [andreyryabin/sprint.migration#134]
Здравствуйте! Очень не хватает метаинформации о миграции:

- кем создана USER_ID
- когда создана DATETIME
- кем установлена USER_ID
- когда установлена DATETIME

столкнулся с тем что пришлось искать причину бага, в итого баг связан с БД, нашел вроде файл миграции, но он только лишь добавляет инфоблок, а где миграция с импортом данных? Тяжело искать... Если бы была эта информация, было бы проще "найти концы"... 

Добавьте пожалуйста.

**Comment by andreyryabin** [comment]
здравствуйте, это есть в версии 4.9 , только там не USER_ID а LOGIN
