### ISSUE TITLE
Не корректно генерируется saveStatuses.

### ISSUE THREAD

**Issue by SkeitOl** [andreyryabin/sprint.migration#137]
Версия модуля  4.10.2

При создании миграции для "Веб-формы" через "Создать миграцию для веб-формы"

Не добавляется поле DEFAULT_VALUE (Присваивать данный статус всем новым документам по умолчанию)
Приходится добавлять в ручную.
![image](https://github.com/andreyryabin/sprint.migration/assets/91635881/5ed162eb-8f1c-4d5d-a228-06d22663bb44)

Из-за этого форма не отправляется выходит ошибка "Не определен статус для нового результата."

**Comment by andreyryabin** [comment]
исправлено в версии 4.10.4
