### ISSUE TITLE
Ошибка в передаче аргумента

### ISSUE THREAD

**Issue by zahirKulembetov** [andreyryabin/sprint.migration#142]
Добрый день! 
Подскажите, это ошибка из-за обновления битрикса? Версию откатывать не хочется, в более старых версиях есть уязвимости, через которые могут взламывать сайт
Или же мне нужно ждать правки в решении с вашей стороны?

[TypeError] mysqli::real_escape_string(): Argument #1 ($string) must be of type string, array given (0) in /var/www/u0363356/data/www/creativepro.su/bitrix/modules/main/lib/db/mysqlisqlhelper.php:405
#0 mysqli::real_escape_string(
array (
  'ELEMENT' => '2572',
  'SUB_VAL_IDS' => 
  array (
    129 => '10200',
    130 => '10416',
    131 => '24227',
    141 => '26076',
  ),
  'SUB_VALUES' => 
  array (
    'TAB_BLOCK_TITLE_1' => 
    array (
      'ID' => '129',
      'TIMESTAMP_X' => '2024-10-17 14:07:42',
      'IBLOCK_ID' => '21',
      'NAME' => 'Заголовок',
      'ACTIVE' => 'Y',

**Comment by zahirKulembetov** [comment]
Понял в чем проблема
Не совместимость с решением https://marketplace.1c-bitrix.ru/solutions/simai.complexprop/
Составные свойства
Я так понимаю, такой перенос только вручную)

**Comment by andreyryabin** [comment]
Добрый день, вообще я делал исправления для совместимости  с этим модулем, они касались переноса элементов. тут видимо что-то другое. прикрепите код миграции я посмотрю.

**Comment by zahirKulembetov** [comment]
Все, перенос элементов проходит, тип свойства не были перенесены
Пытался записать массив на обычный текстовый тип
После установки типа на Составной, все заработало
Единственное данные внутрь составного свойства не записываются, эту часть наверное надо либо дописать самом, либо переносить ручками
