### ISSUE TITLE
Некорректная работа модуля с символическими ссылками Windows

### ISSUE THREAD

**Issue by osc-yakupov** [andreyryabin/sprint.migration#31]
Ось: Windows
Сервер: OSPanel 5.2.2
Версия модуля: 3.10.1 (composer)

Сервер обращается к проекту через символическую ссылку (Junction связь)

Ошибка: 
> Can't create directory E:/OSPanel/domains/abc.localD:\OS Projects\domains\abc.local\local\php_interface\migrations.archive\

![image](https://user-images.githubusercontent.com/42068828/68789957-3e4fbd00-0668-11ea-8ab2-b53dec8e1b24.png)

P.S. Причина по которой проект находится на другом диске - SSD. Сервер расположен на HDD.

**Comment by andreyryabin** [comment]
Здравствуйте, в качестве хотфикса переопределите архивную конфигурацию
создайте файл local/php_interface/migrations.archive.php

и пропишите в нем явно где будут находиться архивные миграции

`
<?php return array (
  'migration_dir' => '/local/php_interface/migrations.archive',
  'migration_table' => 'sprint_migration_archive',
);
`
