### ISSUE TITLE
Не генерируется миграция для ИБ

### ISSUE THREAD

**Issue by skDYLAN** [andreyryabin/sprint.migration#33]
Если нет пользовательских свойств в ИБ и стоит галочка в группе настроек "Свойства инфоблока", то при попытке сгенерировать миграцию ничего не происходит, если убрать галочку, то все чудесно создается.

**Comment by andreyryabin** [comment]
Убирайте галочку тогда :)

**Comment by skDYLAN** [comment]
Это то да +))
Просто заметил такою проблемку в интерфейсе

**Comment by andreyryabin** [comment]
Не думаю что это стоит исправлять, такая особенность формы - когда ставишь галочку выбрать свойства предлагается выбрать их, и если их не выбирать, потому что их нет, миграция не создается
