### ISSUE TITLE
Проблема с кодировкой миграции на проектах CP1251

### ISSUE THREAD

**Issue by EASemashko** [andreyryabin/sprint.migration#34]
Есть проект с кодировкой CP1251
При миграции элементов происходит восстановление миграции в неверной кодировке.
https://i.imgur.com/2cvstzX.png

оба проекта на windows-1251 , но миграция создается в utf-8

**Comment by andreyryabin** [comment]
напишите как будет время, подебажим

**Comment by andreyryabin** [comment]
к сожалению поддержка этой кодировки занимает много ресурсов, временно отключил формочки переноса данных для нее
