### ISSUE TITLE
Встроенный сканер безопасности ругается на статическую уязвимость

### ISSUE THREAD

**Issue by maglor** [andreyryabin/sprint.migration#39]
Встроенный сканер безопасности ругается на статическую уязвимость.

Файл: /local/modules/sprint.migration/admin/steps/schema_import.php
Cross-Site Scripting
46: echo $_POST['step_code']

**Comment by andreyryabin** [comment]
Спасибо, поправлю код чтобы пропускал сканер, уязвимостью это не является так как выше по коду есть проверка чем может быть $_POST['step_code']

**Comment by andreyryabin** [comment]
судя по всему у вас установлена старая версия модуля, обновите ее через маркетплейс или composer
