### ISSUE TITLE
Ошибка при проверке изменений «AgentHelper::saveAgent: requred key "MODULE_ID" empty»

### ISSUE THREAD

**Issue by Dok11** [andreyryabin/sprint.migration#41]
![image](https://user-images.githubusercontent.com/2697890/84130992-a45cc100-aa4c-11ea-9563-8b24e6abfc96.png)

**Comment by andreyryabin** [comment]
в схеме агентов, у одного агента нет обязательного поля, добавьте его в схему

**Comment by Dok11** [comment]
У одного из агентов не указан модуль, он кстати не является обязательным полем

![image](https://user-images.githubusercontent.com/2697890/84131544-5b593c80-aa4d-11ea-96c8-dce9a540a8d4.png)

**Comment by Dok11** [comment]
> в схеме агентов, у одного агента нет обязательного поля, добавьте его в схему

Корректно ли проверять на наличие необязательное поле?

**Comment by Dok11** [comment]
![image](https://user-images.githubusercontent.com/2697890/84132191-3e713900-aa4e-11ea-8596-565d272cb1ff.png)

Судя по админке, обязательные поля — NEXT_EXEC и NAME. Может быть ошибка в коде проверки?

**Comment by andreyryabin** [comment]
Оно обязательное с точки зрения модуля, в битриксе да, заполнять не обязательно, но например и код инфоблока тоже можно не заполнять, однако без него модуль работать не будет, ему нужно идентификатор сущности без привязки к ID

такая же ситуация и с агентами, хелпер, который работает в схемах и миграциях
https://github.com/andreyryabin/sprint.migration/blob/master/lib/helpers/agenthelper.php

для поиска агента использует поля MODULE_ID и NAME, по нему он находит такой же агент в соседней бд и обновляет\удаляет его

**Comment by Dok11** [comment]
Спасибо, стало понятно

**Comment by andreyryabin** [comment]
изменено в 4.9.8 теперь агенты можно создавать без привязки к модулю
