### ISSUE TITLE
Проблема при переносе свойств инфоблока типа список

### ISSUE THREAD

**Issue by asolopovfromcoders** [andreyryabin/sprint.migration#47]
Переносил инфоблок. Много полей типа список. После переноса обнаружилось, что теряется первый вариант значений списка. То есть, в коде миграции, например, вот что: 
`  'VALUES' => 
  array (
    array (
      'VALUE' => 'Кошка',
      'DEF' => 'Y',
      'SORT' => '500',
      'XML_ID' => 'CAT',
    ), 
    array (
      'VALUE' => 'Собака',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => 'DOG',
    ),
  ),`

На выходе в свойство импортируется только значение "Собака". И так по всем подобным свойствам. Кроме того, что эти свойства список, они ещё и множественные, если это важно.

**Comment by andreyryabin** [comment]
интересно, можете код миграции прикрепить?

**Comment by andreyryabin** [comment]
не воспроизвел на новых версиях модуля
