### ISSUE TITLE
Добавить в миграции свойств перенос параметров отображения для списка и детальной

### ISSUE THREAD

**Issue by w1cerg** [andreyryabin/sprint.migration#49]
При использовании миграции для переноса свойств инфоблоков, не переносятся параметры для отображения.

![image](https://user-images.githubusercontent.com/5260476/95181551-e1f40f80-07dc-11eb-8008-a33cdeac6ff8.png)

Важно: не у всех свойств есть строка "Значение добавляется в корзину", это стоит учесть.

**Comment by andreyryabin** [comment]
решено в 3.29.1
