### ISSUE TITLE
При использовании симлинков не заводится

### ISSUE THREAD

**Issue by ProklUng** [andreyryabin/sprint.migration#50]
При структуре: sites/s1/ -> document-root. Симлинки - sites/s1/local -> /local к $values['migration_dir'] в versionconfig.php добавляется еще один document_root. Тут:

       if (empty($values['migration_dir'])) {
            $values['migration_dir'] = Module::getPhpInterfaceDir() . '/migrations';
        } elseif (empty($values['migration_dir_absolute'])) {

            //$values['migration_dir'] = Module::getDocRoot() . $values['migration_dir'];
            // $values['migration_dir'] = $values['migration_dir'];
        }

Помогает комментирование. 

Еще не нашел, где устанавливается migration_dir_absolute (это могло бы помочь избежать правки)

**Comment by andreyryabin** [comment]
здравствуйте, посмотрите пример https://github.com/andreyryabin/sprint.migration/issues/31

создайте конфиг и укажите там migration_dir_absolute = true если вам поможет

**Comment by ProklUng** [comment]
Спасибо. Помогло.
