### ISSUE TITLE
Добавить возможность произвольной выборки элементов инфоблока в миграцию

### ISSUE THREAD

**Issue by Pum-purum** [andreyryabin/sprint.migration#51]
Сейчас, закрывая задачу в Jira, я пишу туда все контентные действия в админке, чтобы после тестирования не вспоминать, что и где делалось. Это жутко неудобно, неизбежны потери и кривотолки. Необходимо дать возможность все действия в рамках одной задачи заталкивать по нескольким простым миграциям. Думаю, будет вполне достаточно сделать поле ввода для указания через запятую всех необходимых символьных или внешних кодов элементов.

**Comment by andreyryabin** [comment]
решено в 3.22.2

**Comment by vahitovOM** [comment]
/**
     * @return bool
     * @throws LoaderException
     */
    protected function InitMigrationInstaller(): bool
    {
        global $APPLICATION;

        if (Loader::IncludeModule('sprint.migration')) {

            $info = CModule::CreateModuleObject('sprint.migration');
            $minVer = '3.25.1';
            if ($info && CheckVersion($info->MODULE_VERSION, $minVer)) {
                $this->migrationInstaller = new Installer(
                    [
                        'migration_dir' => __DIR__ . '/migrations/',
                        'migration_dir_absolute' => true,
                    ]
                );
            } else {
                $APPLICATION->ThrowException("Update sprint.migration module (minimal {$minVer})");
                return false;
            }
        } else {
            $APPLICATION->ThrowException('Install sprint.migration module');
            return false;
        }

        return true;
    }
