### ISSUE TITLE
Cделать публичный метод для установки миграций с кастомным\временным конфигом

### ISSUE THREAD

**Issue by vahitovOM** [andreyryabin/sprint.migration#54]
Что-то типа такого чтобы можно было делать:

$console = new Sprint\Migration\Console($argv, ['migration_dir'=>/my_module/migrations/']);
$console->commandUp();

**Comment by andreyryabin** [comment]
Получается что-то вроде такого кода

`
    function DoInstall()
    {
        if (\CModule::IncludeModule('sprint.migration')) {
            try {
                (new Sprint\Migration\Installer(
                    [
                        'migration_dir'          => __DIR__ . '/migrations/',
                        'migration_dir_absolute' => true,
                    ]
                ))->install();
            } catch (\Exception $e) {
                global $APPLICATION;
                $APPLICATION->ThrowException($e->getMessage());
                return false;
            }
        }

        RegisterModule($this->MODULE_ID);
        return true;
    }
`

**Comment by andreyryabin** [comment]
дополнил вики https://github.com/andreyryabin/sprint.migration/wiki/Интеграция-со-сторонними-модулями
