### ISSUE TITLE
"Неверный тип события" при миграции форм

### ISSUE THREAD

**Issue by SergeyBeloglazovRL** [andreyryabin/sprint.migration#55]
После расхождения прода и теста по почтовым шаблонам (видимо), при миграции на прод столкнулся с ошибкой "Неверный тип события" при миграции одной из форм.

Вылечилось путём комментирования arMAIL_TEMPLATE с ID почтовых шаблонов в параметрах миграции. Форма смигрировалась, нужные почтовые шаблоны подцепились, т.к. MAIL_EVENT_TYPE у них символьный. Только, разумеется, без галочек использования.

Может сделать выгрузку почтовых шаблонов опциональной, по галочке?

**Comment by andreyryabin** [comment]
да, ок, возьму в работу

**Comment by SergeyBeloglazovRL** [comment]
Спасибо!

**Comment by andreyryabin** [comment]
решено в 4.2.1, заменил id в массиве arMAIL_TEMPLATE  на сообщение и тип события
