### ISSUE TITLE
Не импортируется агент с прошлогодней датой

### ISSUE THREAD

**Issue by SergeyBeloglazovRL** [andreyryabin/sprint.migration#56]
При попытке импортировать агента с прошлогодней датой следующего запуска, выдаётся ошибка "Неверная дата". Если дату заменить на будущую - всё ОК.

**Comment by andreyryabin** [comment]
эту ошибку выдает битрикс, можно делать в модуле такую проверку самостоятельно и заменять дату если она старая, но не хочется навешивать доп логику, решать за программиста добавлять ли этот агент

**Comment by SergeyBeloglazovRL** [comment]
Возможно. В функции AddAgent я никаких ограничений не вижу. Также при ручной установке параметров указывал прошедшую дату, чтобы агент запустился. Раньше при переносе агентов с такой проблемой не сталкивался. Применить попытался очень старые миграции.
Проблема, как я понимаю, может возникать и в других случаях, если миграция применяется не сразу, а через некоторое время.
Сообщение об ошибке достаточно очевидное, т.ч. можно и ничего не делать. Либо какие-то примечания в инструкции по этому поводу написать.

**Comment by andreyryabin** [comment]
ок. попробуйте разобраться тогда в каких случаях можно сохранить агент со старой датой, а в каких нет, попробуем какой-то общий подход сформировать

**Comment by SergeyBeloglazovRL** [comment]
Хорошо, напишу детали, если появятся.
