### ISSUE TITLE
Не перенеслись данные из свойства типа HTML/текст

### ISSUE THREAD

**Issue by SergeyBeloglazovRL** [andreyryabin/sprint.migration#60]
Не перенеслись данные из свойства типа HTML/текст, хотя в xml данные есть.
Миграции выполнил на 2 серверах, оба раза данные в это поле не перенеслись.
Версия модуля: 3.25.1 
PHP 7.4
mbstring.func_overload отключена

**Comment by andreyryabin** [comment]
здравствуйте, обновитесь до 3.27.1 там исправлено

**Comment by SergeyBeloglazovRL** [comment]
Спасибо, учту.
В marketplace.1c-bitrix.ru пока 3.25.1 самая последняя.

**Comment by andreyryabin** [comment]
да, я обновлю сегодня завтра

**Comment by SergeyBeloglazovRL** [comment]
Спасибо!

**Comment by andreyryabin** [comment]
решено в 3.28.3
