### ISSUE TITLE
Выход с сообщением "Файл для переноса данных был создан в более ранней версии модуля"

### ISSUE THREAD

**Issue by ProklUng** [andreyryabin/sprint.migration#62]
Когда в CLI режиме мигратор обламывается с сообщением вида "Файл для переноса данных был создан в более ранней версии модуля" не указывается - в каком именно файле случилась такая беда,  что крайне неудобно. Пришлось лезть в код IblockElementsImport и смотреть. Оказалось, - что неудивительно, - вся информация о файле есть. Если переписать выход как-то так:

                $this->exchangeEntity->exitWithMessage(
                    Locale::getMessage('ERR_EXCHANGE_VERSION') . ': ' . $this->getExchangeFile()
                );
            }

то уже становится значительно лучше.

Upd. Тоже самое касается сообщений вида "IblockTrait::getIblockIdIfExists: Инфоблок не найден". Какой инфоблок? В каком файле? Нет ясности.

Попутно вопрос с этими версиями файлов. Кажется, такой подход (не в пределах мажорной версии хотя бы) излишне радикален. Насоздавал миграций сто штук на версии 3.19 (условно), живу и горя не знаю. Потом пусканул композер и прилетела версия 3.33. Неужто почти все мои миграции тут же протухают? Неужто надо лочить на определенную версию? Возможно, чего-то недопонял и это как-то настраивается?

P.S. Маленький апдейт: у меня почему-то сгенерировался xml файл без параметра exchangeVersion, потому и обламывалось. Добавил - стало OK. Вроде, генерил его через админку, но ....

**Comment by andreyryabin** [comment]
Спасибо, поправлю текст ошибки.
Подход не радикален потому что текст ошибки вводит в заблуждение, имеется ввиду версия импорта exchangeVersion, она меняется не с каждым обновлением модуля, а когда меняется формат выгрузки. сейчас это версия exchangeVersion=2 в нем в xml контент сложных свойств  типа html\text или кастомных свойств,  хранится в json, в отличие от сериализованной строки как раньше, с которой были проблемы

**Comment by andreyryabin** [comment]
Такая фраза думаю будет понятнее
"Файл для переноса данных \"#NAME#\" не поддерживается текущей версией модуля.\nПожалуйста создайте его заново."

по крайней мере не будет казаться что выгрузка жестко привязана к определенной версии модуля

**Comment by ProklUng** [comment]
Спасибо за ответы.  Жду апдейт ;-)

Обновляю через композер.  Но миграции делал через админку - причем эту, проблемную, когда-то достаточно давно, в порядке эксперимента. Более свежие экземпляры миграций содержат этот ключ в XML. Скорее всего, это какой-то случайный сбой. Но в целом, может имеет смысл exchangeVersion как-нибудь обозначить по умолчанию для случаев, если этого ключа нет.

**Comment by andreyryabin** [comment]
если композер - то я уже выкатил 3.28.5, в маркете чуть позже появится, атрибут exchangeVersion как раз недавно появился, в старых импортах его нет и их надо будет пересоздать

**Comment by ProklUng** [comment]
Спасибо еще раз. Закрываю.
