### ISSUE TITLE
Ошибка построение списка свойств инфоблока для миграций

### ISSUE THREAD

**Issue by dimonvelsk** [andreyryabin/sprint.migration#65]
Ошибка: IblockTrait::getIblockUid: Инфоблок не найден
Ошибка возникает когда в свойствах ИБ есть привязка к элементам(разделам) у ИБ которых нет символьного кода.
Но это не позволяет выбрать другие свойства для миграции. Что вызывает неудобство. Возможно есть смысл показывать такие свойства на следующем шаге просто disabled - но давать выбрать другие?
 
https://prnt.sc/13i68hb

**Comment by andreyryabin** [comment]
Да, стоит поправить, спасибо

**Comment by andreyryabin** [comment]
решено в 3.28.8
