### ISSUE TITLE
Добавить информации в сообщение об ошибке "HlblockHelper::getHlblockUid: Highload-блок не найден"

### ISSUE THREAD

**Issue by AlexandrKhurs** [andreyryabin/sprint.migration#68]
Если свойство инфоблока некорректно настроено (свойство типа "справочник" содержит ссылку на несуществующий ХЛ-блок) - модуль при попытке создать/импортировать схему данных закономерно выдает ошибку. Но сам текст ошибки не содержит информации о том, какое свойство какого инфоблока ссылается "вникуда". 
(в моем случае, дословно текст выглядел так:  "HlblockHelper::getHlblockUid: Highload-блок не найден" )
Если добавить в сообщение информацию об инфоблоке и проблемном свойстве - это сильно поможет в поиске ошибок.

PS причем, некорректная ссылка на несуществующий инфоблок (а не хайлоад-блок) подобной ошибки не вызывает вообще.

**Comment by Arkharis** [comment]
Сам вчера потратил время на поиск причины ошибок "IblockTrait::getIblockUid: Инфоблок не найден".
В одном случае, это было отсутствие символьного кода у инфоблока, в другом - откуда-то взявшийся код сущности "IBLOCK_0_SECTION" у пользовательского поля.

Готовлю pull request, в котором планирую ловить дополненные исключения из getIblockUid() в prepareExportUserTypeEntity() и выбрасывать снова с добавленной информацией о пользовательском поле.

Например:
`UserTypeEntityHelper::prepareExportUserTypeEntity: Ошибка экспорта пользовательского поля "88":
IblockTrait::getIblockUid: Инфоблок "0" не найден`

**Comment by andreyryabin** [comment]
выкатил ваш ПР в версии 3.29.1 спасибо!
