### ISSUE TITLE
Похоже, что не переносятся "параметры свойств инфоблока"

### ISSUE THREAD

**Issue by AlexandrKhurs** [andreyryabin/sprint.migration#69]
При переносе настроек ИБ (пробовал и через миграции, и через схемы данных) сами инфоблоки переносятся, со всеми параметрами, но вот эти новые параметры (которые переопределяют отображение в компонентах) - похоже, теряются по пути.

![image](https://user-images.githubusercontent.com/25723814/133316425-1afc2493-0df4-4d54-a248-632ff0b2c901.png)

**Comment by andreyryabin** [comment]
решено в 3.29.1
