### ISSUE TITLE
Новая миграция не отображается в списке

### ISSUE THREAD

**Issue by chaevnicher** [andreyryabin/sprint.migration#7]
ну что за дичь)
пофиксите пожалуйста
sprint.migration/admin/assets/script.js

кнопка "Создать миграцию" перезагружает страницу, миграция не появляется в списке, не находится при поиске.

какая версия предыдущего релиза? пропишу жестко, а то не тестируете...

**Comment by andreyryabin** [comment]
Jquery будто не подключена, есть ошибки в консоли браузера?

**Comment by andreyryabin** [comment]
Версии есть на вкладке что нового вот тут http://marketplace.1c-bitrix.ru/solutions/sprint.migration/#tab-log-link

**Comment by chaevnicher** [comment]
в текущей версии либу jquery нужно дополнительно в админку пропихивать? ну ооок. до этого-то все идеально работало.

**Comment by andreyryabin** [comment]
пропихивать ничего не нужно, jquery используется системная 
в bitrix/modules/sprint.migration/admin/sprint_migrations.php
\CUtil::InitJSCore(Array("jquery"));

**Comment by andreyryabin** [comment]
напишите в скайп ryabina_sl, созвонимся, посмотрю что у вас на проекте за ошибка такая
