### ISSUE TITLE
AgentHelper::saveAgent: Обязательное поле "MODULE_ID" не заполнено

### ISSUE THREAD

**Issue by Isa3v** [andreyryabin/sprint.migration#81]
![image](https://user-images.githubusercontent.com/30827684/147091674-4c7b5cdc-c17c-42c1-906e-35a68b5bd591.png)

У агентов поле MODULE_ID не является обязательным

**Comment by andreyryabin** [comment]
добрый день, верно, я описывал причины тут https://github.com/andreyryabin/sprint.migration/issues/41

может быть действительно надо оставить только name, только придется переделать всё что связано с этим хелпером, схемы, билдеры

**Comment by andreyryabin** [comment]
изменено в 4.9.8 теперь агенты можно создавать без привязки к модулю
