### ISSUE TITLE
Кастумное именование свойств в списках ИБ

### ISSUE THREAD

**Issue by Sinator** [andreyryabin/sprint.migration#82]
В методе: $helper->UserOptions()->saveElementGrid();
В элементе массива "custom_names" при указании ['PROPERTY_КОД' => 'Custom name'] не происходит автоматического преобразования "PROPERTY_КОД" в "PROPERTY_ИД" из-за чего не изменяется имя в колонке.

**Comment by andreyryabin** [comment]
решено в 4.2.1
