### ISSUE TITLE
Перехват ошибок без вывода где она произошла

### ISSUE THREAD

**Issue by Sinator** [andreyryabin/sprint.migration#85]
При миграции может произойти ошибка, которая перехватывается модулем и выводится только сообщение, без трассировки из-за чего не всегда понятно где она произошла и приходится самостоятельно выискивать конкретный кусок кода с ошибкой, либо оборачивать все тоже в try с отловом Throwable.

Обработка и вывод ошибки происходит тут:
./local/modules/sprint.migration/lib/versionmanager.php:125 > ./local/modules/sprint.migration/admin/steps/migration_execute.php:88

**Comment by Sinator** [comment]
Дублирует Issue #83

**Comment by andreyryabin** [comment]
частично решено в 4.1.1
