### ISSUE TITLE
Блокировка интерфейса

### ISSUE THREAD

**Issue by Sinator** [andreyryabin/sprint.migration#86]
В момент выполнения миграции не блокируется интерфейс управления конкретной миграцией и если не обратить внимания на кнопку "Установить новые", которая в этот момент disabled, то можно натыкать попутных действий через "гамбургер" миграций в списке.
PS: возможно не блокируется и "гамбургер" около кнопки "Установить новые".
ЗЫ: наверно было бы не плохо еще добавить индикатор загрузки в окно лога, например как в командной строке php

**Comment by andreyryabin** [comment]
решено в 4.1.1
