### ISSUE TITLE
Миграции элементов в разделы c одинаковыми наименованиями

### ISSUE THREAD

**Issue by reygasai** [andreyryabin/sprint.migration#89]
Существует проблема связанная с переносом элементов в инфоблок, где имеются одинаковые наименования разделов. Например, если у нас существует 2 раздела с одинаковым наименованием, то элементы попадут в один из них. 

Предложение: добавить работу с символьным кодом раздела, например при создании миграции для элементов будет чекбокс (например "дополнительно использовать привязку элементов к символьному коду раздела") чтобы при миграции приоритет отдавался не только наименованию раздела, но и его символьному коду.

**Comment by andreyryabin** [comment]
поправлю 
https://github.com/andreyryabin/sprint.migration/blob/fbc126889a84f4b91fde592e96a51a78356ebac7/lib/helpers/traits/iblock/iblocksectiontrait.php#L348
доработаю метод получения уникального названия секции return $section['NAME'] . '|' . (int)$section['DEPTH_LEVEL'];

**Comment by andreyryabin** [comment]
решено в 4.1.1
