### ISSUE TITLE
Зависимости миграций

### ISSUE THREAD

**Issue by goliaf15** [andreyryabin/sprint.migration#92]
Сделать возможность добавлять зависимость одной миграции от другой.
Таким образом можно указать, что создаваемая миграция зависит от другой и может быть установлена только при установленной заданной.

**Comment by andreyryabin** [comment]
решено в 4.2.1 , добавлен свойство и метод помогающий ограничить запуск миграции в зависимости от установки другой

`
class Version20221209140019 extends Version
{
    protected $requiredVersions = ['Version1', Version20221209140011::class];

    /**
     * @throws MigrationException
     */
    public function up()
    {
        $this->checkRequiredVersions(['Version1', Version20221209140011::class]);
    }
}
`
