### ISSUE TITLE
Возобновление длительной миграции

### ISSUE THREAD

**Issue by Sinator** [andreyryabin/sprint.migration#95]
При обрыве сети или других проблем длительная миграция с шагами обрубается и нет возможности ее возобновить, приходится опять 3 часа ждать с нуля.

Нужно реализовать кнопку "возобновить".

**Comment by andreyryabin** [comment]
решено в 4.2.1, в админке добавлена кнопка "Запустить снова" в случае если миграция запустилась с ошибкой,
если это была пошаговая миграция, она продолжится с того же места
