### ISSUE TITLE
Добавить параметр в конфигурацию, для изменения базовой директории Файлов миграций

### ISSUE THREAD

**Issue by casnerano** [andreyryabin/sprint.migration#98]
При создании миграций элементов иб, может быть выгружено множество привязанных файлов и картинок.
Не всегда удобно их держать в основном репозитории.
Нужна возможность переопределить стандартную директорию, где сохраняются такие файлы миграций, чтобы можно было отделить от самих файлов миграций.

**Контекст**
Обсуждали в телеге, сказал, что можно достаточно просто сделать, переопределив `getExchangeDir()`.

**Comment by andreyryabin** [comment]
решено в 4.2.1 параметром в конфиге exchange_dir = "путь до директории где хранятся xml-выгрузки и картинки"
